app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
// \Carbon\Carbon::setLocale('en');


if(isset($_COOKIE['Language'])){
	session(['languageActive' => $_COOKIE['Language']]);
} else {
	session(['languageActive' => 'English']);
	setcookie("Language", 'English', time()+3600*24*365, '/');
}
//Route::group(array('middleware'=>['inconstruction', 'configsite']), function(){
/*Route::group(array('middleware'=>['configsite']), function(){

	Route::get('/', ['as' => 'home', "uses"=> "FrontendController@home"]);
	
	Route::get('/eve/{num}', ['as' => 'voirEvent', 'uses' => 'FrontendController@view']);
	Route::get('api/setCity/{city}', ['as' => 'setCity', 'uses' => 'FrontendController@setCity']);
	// Route::get('api/setLanguage/{language}', ['as' => 'setLanguage', 'uses' => 'FrontendController@setLanguage']);
	Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
	Route::post('api/storeEvent/{language}', ['as' => 'storeEvent', 'uses' => 'FrontendController@storeEvent']);
	Route::get('events/cat/{id}', ['as'=>'pageCat', 'uses'=>'Frontend\FrontendController@pageView']);
	
	Route::get('profile/{email}', ['as' => 'profile', 'uses' => 'ProfileController@edit']);
});
*/
//frontend route
Route::group(array('middleware' => ['configsite']), function(){
	Route::get('/', 'Frontend\FrontendController@home');
	Route::post('/event/comment', 'Frontend\FrontendController@comment');
	Route::get('/event/{num}', ['as' => 'viewEvent', 'uses' => 'Frontend\FrontendController@view']);
	
	Route::get('/eve/{num}', ['as' => 'voirEvent', 'uses' => 'FrontendController@view']);
	Route::get('api/setCity/{city}', ['as' => 'setCity', 'uses' => 'FrontendController@setCity']);
	// Route::get('api/setLanguage/{language}', ['as' => 'setLanguage', 'uses' => 'FrontendController@setLanguage']);
	Route::get('lang/{lang}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);
	Route::post('api/storeEvent/{language}', ['as' => 'storeEvent', 'uses' => 'FrontendController@storeEvent']);
	Route::get('events/cat/{id}', ['as'=>'pageCat', 'uses'=>'Frontend\FrontendController@pageView']);

	Route::get('agenda', 'Frontend\FrontendController@agenda');
	
	Route::get('profile/{email}', ['as' => 'profile', 'uses' => 'ProfileController@edit']);


});

Route::get('login', ['as'=>'login', 'uses' => function(){
	return view('auth.login');
}]);
Route::get('auth/logout', 'Auth\AuthController@getLogout');
Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);

Route::get('login/{provider?}', 'Auth\AuthController@login');
//Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::group(['prefix' => 'backend', 'middleware'=>['auth','configsite']], function () {
	Route::get('home', function(){
	 	return view('backend.home');
	});
	
	Route::get('/', 'Backend\CheckRoleUser@index');

	Route::get('api/enregistrerChangeEvent', ['as' => 'enregistrerChangeEvent', 'uses' => 'BackendController@enregistrerChangeEvent']);

	Route::get('api/enregistrerChangeEnd', ['as' => 'enregistrerChangeEnd', 'uses' => 'BackendController@enregistrerChangeEnd']);

	Route::resource('events', 'Backend\EventController');
	Route::resource('categories', 'Backend\CategoriesController');
	Route::resource('tomoderate', 'ModerateController@index');
	Route::resource('whats', 'WhatController');
	

	Route::get('filemanager', function(){
		return view('backend.filemanager.index');
	});
	Route::get('calendar', function(){ return view('backend.events.calendar');});
	Route::get('tests', 'TestsController@index');
	
	//user
	Route::resource('users', 'Backend\UserController');
	Route::get('changePassword', ['as' => 'changePassword', 'uses' => 'UserController@changePassword']);
	Route::post('updatePassword', ['as' => 'updatePassword', 'uses' => 'UserController@updatePassword']);
	Route::resource('user_group', 'Backend\RoleController');
	Route::get('user_group/permission', 'Backend\RoleController@show');
	Route::post('role_update', 'Backend\RoleController@updateRolePermission');
	
	//config
	Route::resource('configs', 'Backend\ConfigController');
	Route::resource('config_group', 'Backend\ConfigGroupController');
	
});

Route::group(['prefix' => 'advertiser', 'middleware'=>['auth','configsite']], function () {
	Route::get('/advertiser/', function(){
	 	return view('advertiser.home');
	});
});

Route::group(['prefix' => 'sponsor', 'middleware'=>['auth','configsite']], function () {
	Route::get('/', function(){
	 	return view('sponsor.home');
	});
});

Route::group(['prefix' => 'partner', 'middleware'=>['auth','configsite']], function () {
	Route::get('/', function(){
	 	return view('partner.home');
	});
});

Route::get('/deploy', function () {
    // Artisan::call('gitpull:pull');
    // exec('cd /usr/share/nginx/html/', $output);
	$output = "test ici";
    // Discard any changes to tracked files since our last deploy
    // exec('git reset --hard HEAD', $output);

    // Update the local repository
    exec('git pull ssh://git@bitbucket.org/w3cambodia/w3cambodia.git', $output);
    echo 'PULL Request '.implode(' ', $output);
});

app/Models/Backend/ActivityLog.php
<?php namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class ActivityLog extends Model {
	//protected $primaryKey = 'bus_id';
	protected $table = 'activity_log';
	protected $fillable = ['user_id',
							'action',
							'menu_code',
							'create_at'
	];
	public $timestamps = false;
	
	public function user(){
		return $this->belongsTo('App\Models\Admin\UserModel','user_id');
	}
	
}

resources/views/backend/config_group/create.blade.php
@extends('backend.layouts.main')

@section('content')
    
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @include('admin.common.message') 
    @include('admin.common.section_header')

    <!-- Main content -->
      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
              
              {!! Form::open(['url' => 'admin/config_group','class'=>'form-horizontal']) !!}
              	<div class="with-border box-header">
	               <h3 class="box-title">{{$view_title}} Form</h3>
	               <div class="pull-right">
		               <span>
			               <button class="btn btn-success" type="submit">
			               		<i class="fa fa-wa fa-save"></i> Save 
			               </button> &nbsp;&nbsp; 
			               <a class="btn btn-default" href ="{{url('admin/config_group')}}">
				               	<i class="fa fa-wa fa-reply"></i> Back to List
			               </a> 
		               </span>
	               	</div>
	              </div><!-- /.box-header -->
	              <!-- form start -->
	              
	               
                <div class="box-body">
                    <div class="form-group">
                      <label  class="col-sm-4 control-label">Name<span class="validate_label_red">*</span></label>
                      <div class="col-sm-4">
                        {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Config Group Name']) !!}
                      </div>
                    </div>                    
                    
                </div><!-- /.box-body -->
                
              {!! Form::close() !!}
            </form>
            </div><!-- /.box -->
          
          </div>
        </div><!-- /.row -->
      </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
  

@endsection

resources/views/backend/config_group/edit.blade.php
@extends('backend.layouts.main')

@section('content')
    
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @include('admin.common.section_header')

    <!-- Main content -->
      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Horizontal Form -->
            <div class="box box-info">
              
              {!! Form::model($config_group,['method' => 'PATCH','class'=>'form-horizontal','route'=>['admin.config_group.update',$config_group->id]]) !!}
              
              	<div class="with-border box-header">
	               <h3 class="box-title">{{$view_title}} Form</h3>
	               <div class="pull-right">
		               <span>
			               <button class="btn btn-success" type="submit">
			               		<i class="fa fa-wa fa-save"></i> Save 
			               </button> &nbsp;&nbsp; 
			               <a class="btn btn-default" href ="{{url('admin/config_group')}}">
				               	<i class="fa fa-wa fa-reply"></i> Back to List
			               </a> 
		               </span>
	               	</div>
	              </div><!-- /.box-header -->
	              <!-- form start -->
                
                 
                <div class="box-body">

                    <div class="form-group">
                      <label  class="col-sm-4 control-label">Name<span class="validate_label_red">*</span></label>
                      <div class="col-sm-4">
                        {!! Form::text('name',null,['class'=>'form-control','placeholder'=>'Name']) !!}
                      </div>
                    </div>   
                </div><!-- /.box-body -->
                
              {!! Form::close() !!}
            </form>
            </div><!-- /.box -->
          
          </div>
        </div><!-- /.row -->
      </section><!-- /.content -->
  </div><!-- /.content-wrapper -->
  
  <script src="{{url('/js/ui/jquery-ui.js')}}"></script>
<script>
  $( "#tabs" ).tabs();
</script>  
  
@endsection

resources/views/backend/config_group/index.blade.php
@extends('Admin.common.layout')

@section('content')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    @include('admin.common.message') 
    <section class="content-header">
      <h1>
        Config Group
        <small> Management</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="#">Config Group</a></li>
        <li class="active">Config</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

          <div class="box">
            <div class="with-border box-header">
             <h3 class="box-title">Config Listing</h3>
             <div class="pull-right">
             	<span>
             		<button class="btn btn-primary" onclick="location.href ='{{url('admin/config_group/create')}}';">
             			<i class="fa fa-wa fa-plus">
             			</i> Add New
             		</button>
             		
             	</spa>
             </div>
            </div><!-- /.box-header -->
            
            <div class="box-body">
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>No.</th>
                   
                   
                    <th>Name</th>
                    
                    <th>Action</th>
                  </tr>
                </thead> 
                <tbody>
                	<?php $i = 1;?>
                  <?php   
                  //print_r($alldata); exit;               
	                foreach($alldata as $data){
	                ?>
	                  <tr>
	                  	<td width="50"><?php echo($i); ?></td>
	                   
	                    <td>{{ $data->name }}</td>
                      
	                    
	                    <td width="250">
	                      <a href="{{route('admin.config_group.edit',$data->id)}}" class="btn btn-primary" title="Edit"><i class="fa fa-pencil"></i></a>
	                      <a href="{{route('admin.config_group.destroy',$data->id)}}" class="btn btn-danger" title="Delete" data-method="delete" data-confirm="Are you sure?">
                          <i class="fa fa-trash"></i>
                        </a>
                      </td>
	                    
	                  </tr>
					       <?php $i++; ?>
	              <?php  }?>
                </tbody>
                
              </table>
            </div><!-- /.box-body -->
          </div><!-- /.box -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </section><!-- /.content -->
  </div><!-- /.content-wrapper -->

@endsection